### ISSUE TITLE
install

### ISSUE THREAD

**Issue by PatrickSteiner** [pivotal-sadubois/tanzu-demo-hub#1]
Wenn ich Deiner Anleitung folge und 

./deployMiniKube  -d minikube-tanzu-demo-hub.cfg

verwende, gibt es den Fehler

RROR: failed to add helm registry https://charts.bitnami.com/bitnami

**Comment by pivotal-sadubois** [comment]
Habe es korrigiert, mache doch bitte ein ‘git pull’ und starte es neu, es sollte nun eine warnung geben einen brew install helm zu machen


---
Sacha Dubois
Senior System Engineer | Vmware Tanzu
+41 79 418 1334<tel://+41794181334> | ***@***.******@***.***> | @sacha-dubois<http://www.linkedin.com/in/sacha-dubois>


From: Patrick Steiner ***@***.***>
Reply to: pivotal-sadubois/tanzu-demo-hub ***@***.***>
Date: Saturday, 20 March 2021 at 19:48
To: pivotal-sadubois/tanzu-demo-hub ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pivotal-sadubois/tanzu-demo-hub] install (#1)


Wenn ich Deiner Anleitung folge und

./deployMiniKube -d minikube-tanzu-demo-hub.cfg

verwende, gibt es den Fehler

RROR: failed to add helm registry https://charts.bitnami.com/bitnami<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcharts.bitnami.com%2Fbitnami&data=04%7C01%7Csdubois%40vmware.com%7C13bb4a2fb1e04c58f7ea08d8ebd0b466%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C1%7C0%7C637518628915442633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4GLq6X1wKMbZ0vCT1lqUu3SwZ%2FdPLPhwaB5MdK%2FjNzk%3D&reserved=0>

**Comment by pivotal-sadubois** [comment]
already fixed in latest release
